### ISSUE TITLE
Add workspace support

### ISSUE THREAD

**Issue by raszi** [gilbertw1/better-jumper#6]
I am not sure that I am opening the issue in the right place but it would be great if better-jumper would support workspaces.

Here is a related issue from hlissner/doom-emacs#2826

**Comment by gilbertw1** [comment]
I'll keep this issue open to track any potentially related issues brought up in the attached thread. However after reviewing it, the "Workspace" you're referring to is a Doom specific concept which `better-jumper` doesn't (and will not) support natively. `better-jumper` does support the underlying mechanisms required for Doom "workspaces".

It appears that the crux of the problems being experienced are due to the initial window created in a workspace copying the previous windows jump list (which was a window in the previous Doom "workspace"). In this scenario, Doom should clear the jump list on the window created for the newly provisioned "workspace".

Here's the related configuration that stipulates what `better-jumper` should do when creating a new window: https://github.com/gilbertw1/better-jumper#new-window-behavior-better-jumper-new-window-behavior

**Comment by raszi** [comment]
Awesome, thank you for the quick turnaround!

**Comment by raszi** [comment]
Awesome, thank you!

**Comment by gilbertw1** [comment]
No problem!

I've added more detail along with a pull request to the corresponding doom issue: hlissner/doom-emacs#2826
